#! /usr/bin/python3
"""
Hardware-capture parsing tests.

Every byte string in this file was captured VERBATIM from a real NanoVNA-F V2
(firmware 0.3.0) via the command() passthrough -- see tests/readme_capture.md
(generated by collect_readme_data.py). We replay those exact device bytes
through the REAL parsing helpers to prove the library cleans and parses true
hardware output, not an idealized synthetic version of it.

Because clean_return strips the echoed-command line (everything up to and
including the first \\r\\n), each capture below is prefixed with a synthetic
echo line ("<cmd>\\r\\n") to reconstruct the full frame clean_return actually
receives. The payload bytes after that are the genuine device output, including
the real 'ch> \\r\\nch> ' doubled-trailing-space prompt tail.

No hardware required to RUN these -- the hardware already ran; this pins its
output so a future change to clean_return that breaks real framing fails here.
"""

import pytest

from nvnapython import nanoVNA


@pytest.fixture
def dev():
    return nanoVNA()


def _frame(cmd, payload_with_prompt):
    """Reconstruct the full device frame: echoed command + payload + prompt."""
    return bytearray(cmd.encode() + b"\r\n" + payload_with_prompt)


# ---------------------------------------------------------------------------
# Scalar / single-line replies -> exact cleaned payload
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("cmd,payload,expected", [
    ("version", b"0.3.0\r\nch> \r\nch> ", b"0.3.0"),
    ("SN", b"20210413080156D7\r\nch> \r\nch> ", b"20210413080156D7"),
    ("resolution", b"800,480\r\nch> \r\nch> ", b"800,480"),
    ("LCD_ID", b"118200\r\nch> \r\nch> ", b"118200"),
    ("edelay", b"0.000000\r\nch> \r\nch> ", b"0.000000"),
    ("sweep", b"50000 3000000000 101\r\nch> \r\nch> ", b"50000 3000000000 101"),
    ("marker", b"1 0 50000\r\nch> \r\nch> ", b"1 0 50000"),
])
def test_scalar_captures_clean_exactly(dev, cmd, payload, expected):
    out = dev.clean_return(_frame(cmd, payload))
    assert bytes(out) == expected


def test_version_reduces_to_bare_string(dev):
    # The README's headline framing-fix claim: 'version' returns exactly '0.3.0'
    # with no surviving prompt tail.
    out = dev.clean_return(_frame("version", b"0.3.0\r\nch> \r\nch> "))
    assert bytes(out) == b"0.3.0"
    assert b"ch>" not in out


def test_info_multiline_payload_preserved(dev):
    raw = (b"Model:        NanoVNA-F_V2\r\n"
           b"Frequency:    50k ~ 3GHz\r\n"
           b"Build time:   Aug 17 2021 - 16:13:15 CST\r\nch> \r\nch> ")
    out = dev.clean_return(_frame("info", raw))
    assert b"ch>" not in out
    assert b"NanoVNA-F_V2" in out
    assert b"50k ~ 3GHz" in out
    # internal newlines between info lines are preserved
    assert out.count(b"\r\n") == 2


def test_cal_status_keeps_internal_and_trailing_text_space(dev):
    # 'cal' with no arg returns "load open short thru cal'ed " -- note the
    # payload itself ends with a space BEFORE the prompt. clean_return strips
    # the prompt block but must not eat payload content.
    raw = b"load open short thru cal'ed \r\nch> \r\nch> "
    out = dev.clean_return(_frame("cal", raw))
    assert bytes(out) == b"load open short thru cal'ed "


# ---------------------------------------------------------------------------
# Error / usage replies survive cleaning (so callers can detect them)
# ---------------------------------------------------------------------------

def test_overmax_error_string_survives(dev):
    # The device's own over-limit error. clean_return must hand it back intact
    # so the library / caller can recognize the rejection.
    raw = b"sweep points exceeds range 11 -201\r\nch> \r\nch> "
    out = dev.clean_return(_frame("scan 1000000 2000000 999 2", raw))
    assert bytes(out) == b"sweep points exceeds range 11 -201"


def test_cwfreq_usage_string_survives(dev):
    # Bare 'cwfreq' prints its (mislabeled-kHz) usage string; pin that we hand
    # it back verbatim -- this is the evidence for the cwfreq units TODO.
    raw = b"usage: cwfreq {frequency(KHz)}\r\nch> \r\nch> "
    out = dev.clean_return(_frame("cwfreq", raw))
    assert bytes(out) == b"usage: cwfreq {frequency(KHz)}"


# ---------------------------------------------------------------------------
# Scan / data: whitespace-separated real/imag pairs, trailing space per line
# ---------------------------------------------------------------------------

def test_scan_outmask2_s11_pairs(dev):
    # outmask 2: S11 pairs, each line "re im " with a TRAILING SPACE, 11 lines.
    raw = (b"1.097607 1.186987 \r\n1.155769 1.300400 \r\n1.228313 1.402045 \r\n"
           b"1.320642 1.491982 \r\n1.431919 1.565192 \r\n1.558024 1.602562 \r\n"
           b"1.692939 1.612919 \r\n1.827417 1.584750 \r\n1.944079 1.523165 \r\n"
           b"2.040512 1.427915 \r\n2.108881 1.318900 \r\nch> \r\nch> ")
    out = dev.clean_return(_frame("scan 1000000 2000000 11 2", raw))
    assert b"ch>" not in out
    lines = [ln for ln in out.decode().split("\r\n") if ln.strip()]
    assert len(lines) == 11
    for ln in lines:
        parts = ln.split()
        assert len(parts) == 2            # exactly a real/imag pair
        float(parts[0]); float(parts[1])  # both parse as floats


def test_scan_outmask1_frequencies(dev):
    raw = (b"1000000 \r\n1100000 \r\n1200000 \r\n1300000 \r\n1400000 \r\n"
           b"1500000 \r\n1600000 \r\n1700000 \r\n1800000 \r\n1900000 \r\n"
           b"2000000 \r\nch> \r\nch> ")
    out = dev.clean_return(_frame("scan 1000000 2000000 11 1", raw))
    lines = [ln for ln in out.decode().split("\r\n") if ln.strip()]
    assert len(lines) == 11
    assert [int(ln) for ln in lines][0] == 1_000_000
    assert [int(ln) for ln in lines][-1] == 2_000_000


def test_scan_outmask6_s11_s21_four_values(dev):
    # outmask 6: S11 + S21 -> 4 values per line (s11_re s11_im s21_re s21_im).
    raw = (b"1.098073 1.185413 0.000053 0.000123 \r\n"
           b"1.152543 1.296921 -0.000052 -0.000138 \r\n"
           b"1.229702 1.403980 -0.000084 -0.000011 \r\nch> \r\nch> ")
    out = dev.clean_return(_frame("scan 1000000 2000000 11 6", raw))
    lines = [ln for ln in out.decode().split("\r\n") if ln.strip()]
    assert len(lines) == 3
    for ln in lines:
        assert len(ln.split()) == 4


def test_scan_outmask7_freq_s11_s21_five_values(dev):
    # outmask 7: freq + S11 + S21 -> 5 values per line.
    raw = (b"1000000 1.098258 1.188245 -0.000036 0.000027 \r\n"
           b"1100000 1.153075 1.299057 -0.000010 0.000002 \r\n"
           b"1200000 1.228164 1.404621 -0.000087 -0.000060 \r\nch> \r\nch> ")
    out = dev.clean_return(_frame("scan 1000000 2000000 11 7", raw))
    lines = [ln for ln in out.decode().split("\r\n") if ln.strip()]
    assert len(lines) == 3
    for ln in lines:
        parts = ln.split()
        assert len(parts) == 5
        int(parts[0])                      # first column is an integer Hz freq
        for p in parts[1:]:
            float(p)


def test_frequencies_command_no_trailing_space(dev):
    # Unlike scan outmask 1, the 'frequencies' command lines have NO trailing
    # space. Pin the distinction so a parser written for one isn't assumed for
    # the other.
    raw = (b"1000000\r\n1100000\r\n1200000\r\n1300000\r\n1400000\r\n"
           b"1500000\r\n1600000\r\n1700000\r\n1800000\r\n1900000\r\n"
           b"2000000\r\nch> \r\nch> ")
    out = dev.clean_return(_frame("frequencies", raw))
    lines = out.decode().split("\r\n")
    lines = [ln for ln in lines if ln]
    assert len(lines) == 11
    assert all(not ln.endswith(" ") for ln in lines)


def test_data_s11_pairs_clean(dev):
    raw = (b"1.007216 -0.004928\r\n0.990002 -0.086659\r\n0.979805 -0.166614\r\n"
           b"-0.594587 -0.252904\r\nch> \r\nch> ")
    out = dev.clean_return(_frame("data 0", raw))
    lines = [ln for ln in out.decode().split("\r\n") if ln.strip()]
    assert len(lines) == 4
    for ln in lines:
        re_, im_ = ln.split()
        float(re_); float(im_)


# ---------------------------------------------------------------------------
# trace dump: TAB-delimited columns (not space) -- different shape from data
# ---------------------------------------------------------------------------

def test_trace_dump_is_tab_delimited(dev):
    raw = (b"0\tLOGMAG\tS11\t10.000000\t7.000000\r\n"
           b"1\tLOGMAG\tS21\t10.000000\t7.000000\r\n"
           b"2\tSMITH\tS11\t1.000000\t0.000000\r\nch> \r\nch> ")
    out = dev.clean_return(_frame("trace", raw))
    lines = [ln for ln in out.decode().split("\r\n") if ln.strip()]
    assert len(lines) == 3
    cols0 = lines[0].split("\t")
    assert cols0[0] == "0"                 # trace IDs are 0-indexed (confirmed)
    assert cols0[1] == "LOGMAG"
    assert cols0[2] == "S11"


# ---------------------------------------------------------------------------
# Round trip through the wire: FakePort -> get_serial_return -> clean_return
# on a genuine capture, proving the read loop + cleaner agree on real bytes.
# ---------------------------------------------------------------------------

def test_full_read_then_clean_on_real_capture():
    from tests.conftest import FakePort
    dev = nanoVNA()
    # genuine 'sweep' capture, including the echoed command the device sends back
    dev.ser = FakePort(b"sweep\r\n50000 3000000000 101\r\nch> \r\nch> ")
    raw = dev.get_serial_return()
    cleaned = dev.clean_return(raw)
    assert bytes(cleaned) == b"50000 3000000000 101"
